# **************************************************
# Copyright (c) 2025, Mayank Mishra
# **************************************************

load_args:
  load_path: /proj/checkpoints/bharat/SUT/save/baseline-swa_v2_3B-MID_TRAIN
  iteration: 25000 

mixed_precision_args:
  # use this if you want to save the unsharded model in specific dtype,
  # if not specified, its taken from the training config in the saved checkpoint
  dtype: bf16

# where to save the HF safetensors checkpoint
unsharded_path:  /proj/checkpoints/bharat/SUT/save_unshard/baseline-swa_v2_3B-MID_TRAIN_25k
